repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest before commit
        entry: pytest
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format